name: Build and Test

on:
  push:
    branches: [ main, develop, c_abi_and_webassembly_interop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]
        compiler:
          - { name: gcc, cc: gcc, cxx: g++ }
          - { name: clang, cc: clang, cxx: clang++ }
          - { name: msvc, cc: cl, cxx: cl }
        exclude:
          # Windows doesn't have these compilers by default
          - os: windows-latest
            compiler:
              name: gcc
              cc: gcc
              cxx: g++
          - os: windows-latest
            compiler:
              name: clang
              cc: clang
              cxx: clang++
          # Linux doesn't have MSVC
          - os: ubuntu-latest
            compiler:
              name: msvc
              cc: cl
              cxx: cl

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.20'

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential

    - name: Setup GCC (Linux)
      if: matrix.os == 'ubuntu-latest' && matrix.compiler.name == 'gcc'
      run: |
        sudo apt-get install -y gcc-10 g++-10
        echo "CC=gcc-10" >> $GITHUB_ENV
        echo "CXX=g++-10" >> $GITHUB_ENV

    - name: Setup Clang (Linux)
      if: matrix.os == 'ubuntu-latest' && matrix.compiler.name == 'clang'
      run: |
        sudo apt-get install -y clang-14
        echo "CC=clang-14" >> $GITHUB_ENV
        echo "CXX=clang++-14" >> $GITHUB_ENV

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Ensure Git is available for FetchContent
        git --version

    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v2

    - name: Ensure VS 2022 Build Tools installed (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        # Ensure vswhere is available to detect existing installations
        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        if (-not (Test-Path $vswhere)) {
          choco install vswhere -y --no-progress
          $vswhere = (Get-Command vswhere.exe).Source
        }

        # Look for Visual Studio 2022 Build Tools (version 17.x)
        $vs2022 = & $vswhere -latest -products Microsoft.VisualStudio.Product.BuildTools -version "[17.0,18.0)" -property installationPath
        if (-not $vs2022) {
          Write-Host "Installing Visual Studio 2022 Build Tools..."
          choco install visualstudio2022buildtools -y --no-progress --timeout 0 --package-parameters '--quiet --wait --norestart --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.CMake.Project --add Microsoft.VisualStudio.Component.Windows10SDK.19041'
        } else {
          Write-Host "Visual Studio 2022 Build Tools already installed at: $vs2022"
        }

    - name: Cache build directory
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-${{ matrix.compiler.name }}-${{ matrix.build_type }}-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.compiler.name }}-${{ matrix.build_type }}-

    - name: Configure CMake (Linux GCC)
      if: matrix.os == 'ubuntu-latest' && matrix.compiler.name == 'gcc'
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_POLICY_VERSION_MINIMUM=3.5

    - name: Configure CMake (Linux Clang)
      if: matrix.os == 'ubuntu-latest' && matrix.compiler.name == 'clang'
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_POLICY_VERSION_MINIMUM=3.5

    - name: Configure CMake (Windows MSVC)
      if: matrix.os == 'windows-latest'
      run: |
        cmake -B build -S . -G "Visual Studio 16 2019" -A x64 -T v143

    - name: Build
      run: |
        cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        cd build
        ctest --build-config ${{ matrix.build_type }} --output-on-failure --verbose
    
    - name: Test shared library build
      shell: bash
      run: |
        echo "Testing shared library artifacts..."
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ls -la build/${{ matrix.build_type }}/ | grep -E "(oglib|\.dll)" || echo "No shared library found"
        else
          ls -la build/ | grep -E "(oglib|\.so)" || echo "No shared library found"
        fi

    - name: Run main executable test
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          if [ -f "./build/${{ matrix.build_type }}/nova_genesis_orbitalguard_test.exe" ]; then
            ./build/${{ matrix.build_type }}/nova_genesis_orbitalguard_test.exe
          else
            echo "Main test executable not found, skipping..."
          fi
        else
          if [ -f "./build/nova_genesis_orbitalguard_test" ]; then
            ./build/nova_genesis_orbitalguard_test
          else
            echo "Main test executable not found, skipping..."
          fi
        fi

    - name: List build artifacts (Debug)
      if: failure()
      shell: bash
      run: |
        echo "Build directory contents:"
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ls -la build/${{ matrix.build_type }}/
        else
          ls -la build/
        fi

  wasm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/c_abi_and_webassembly_interop' || contains(github.event.head_commit.message, '[wasm]')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: 3.1.45
        actions-cache-folder: 'emsdk-cache'

    - name: Verify Emscripten
      run: |
        emcc --version
        em++ --version

    - name: Configure WASM build
      run: |
        emcmake cmake -B build-wasm -S . -DOG_BUILD_WASM=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build WASM module
      run: |
        cmake --build build-wasm --target oglib_wasm

    - name: Verify WASM artifacts
      run: |
        ls -la build-wasm/
        file build-wasm/oglib_wasm.js build-wasm/oglib_wasm.wasm || echo "WASM files not found"

    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm-build
        path: |
          build-wasm/oglib_wasm.js
          build-wasm/oglib_wasm.wasm
